export const FORMATS = {
  YEARS: "YEARS",
  MONTHS: "MONTHS",
  WEEKS: "WEEKS",
  DAYS: "DAYS",
  HOURS: "HOURS",
  MINUTES: "MINUTES",
  SECONDS: "SECONDS",
};

export const PAGES = {
  WEDDING_COUNTDOWN: "WEDDING_COUNTDOWN",
  MARRIAGE_COUNTER: "MARRIAGE_COUNTER",
  RELATIONSHIP_COUNTER: "RELATIONSHIP_COUNTER",
  PERCENT: "PERCENT",
};
