export const FORMATS = {
  YEARS: "YEARS",
  MONTHS: "MONTHS",
  WEEKS: "WEEKS",
  DAYS: "DAYS",
  HOURS: "HOURS",
  MINUTES: "MINUTES",
  SECONDS: "SECONDS",
};

export const PAGES = {
  COUNTDOWN: "COUNTDOWN",
  COUNTER: "COUNTER",
  PERCENT: "PERCENT",
};
